version: '3'

services:
  natours:
    build:
      context: .
      dockerfile: server.dockerfile
    container_name: natours
    environment:
      - DATABASE=mongodb://db:27017/natours
    ports:
      - 80:80
    depends_on:
      - db
  
  
  db:
    container_name: mongodb
    image: mongo
    volumes:
      - ./db-data:/data/db
    ports:
      - 27017:27017
    
    
    



    